//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class ChatroomDetail
    {
        [DataMember]
        public int ChatroomDetailsID { get; set; }
        [DataMember]
        public int ChatroomID { get; set; }
        [DataMember]
        public int UserID { get; set; }
        
        [IgnoreDataMember]
        public virtual Chatroom Chatroom { get; set; }
        [IgnoreDataMember]
        public virtual User User { get; set; }
    }
}
