//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Message
    {
        [DataMember]
        public int MessageID { get; set; }
        [DataMember]
        public int ChatroomID { get; set; }
        [DataMember]
        public int SenderID { get; set; }
        [DataMember]
        public System.DateTime SentDate { get; set; }
        [DataMember]
        public string Text { get; set; }
        [DataMember]
        public byte[] Image { get; set; }

        [IgnoreDataMember]
        public virtual Chatroom Chatroom { get; set; }
        [IgnoreDataMember]
        public virtual User User { get; set; }
    }
}
